#!/bin/bash
START=$1
END=$2
 
for (( c=$START; c<=$END; c++ ))
do
!python -W ignore colab_interpolate.py     --netName DAIN_slowmotion --time_step 0.5 --input_file "/content/drive/MyDrive/Kimetsu no Yaiba - 0$c.mp4" --output_dir /content/drive/MyDrive/DAIN --enable_transcoder 0 --overwrite 0 --upscale_only 0  --selective_interpolation 1 --dual_instance 1   --waifu2x_scale 2 --waifu2x_model ../waifu2x-ncnn-vulkan/models/models-upconv_7_anime_style_art_rgb --ph_this_bad_th 500 --use_debug_parts 0 --debug_nb_parts 0 --intro_skip '0:58-2:30' --ending_skip '21:30-23:41'
done
